// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Snippet struct {
	SnippetID uuid.UUID
	Title     string
	Content   string
	Created   pgtype.Timestamp
	Expires   pgtype.Timestamp
}
