// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSnippet(ctx context.Context, arg CreateSnippetParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteSnippet(ctx context.Context, snippetID uuid.UUID) error
	GetLatestSnippets(ctx context.Context) ([]GetLatestSnippetsRow, error)
	GetLatestSnippetsForUser(ctx context.Context, userID pgtype.UUID) ([]GetLatestSnippetsForUserRow, error)
	GetSnippetByID(ctx context.Context, snippetID uuid.UUID) (GetSnippetByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
