// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO snippets (title, content, created, expires)
VALUES ($1, $2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + CAST($3 AS INTERVAL))
RETURNING snippet_id
`

type CreateParams struct {
	Title     string
	Content   string
	ExpiresIn pgtype.Interval
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, create, arg.Title, arg.Content, arg.ExpiresIn)
	var snippet_id uuid.UUID
	err := row.Scan(&snippet_id)
	return snippet_id, err
}

const getById = `-- name: GetById :one
SELECT snippet_id, title, content, created, expires
 	FROM snippets
 	WHERE expires > NOW()
 	AND snippet_id = $1
`

func (q *Queries) GetById(ctx context.Context, snippetID uuid.UUID) (Snippet, error) {
	row := q.db.QueryRow(ctx, getById, snippetID)
	var i Snippet
	err := row.Scan(
		&i.SnippetID,
		&i.Title,
		&i.Content,
		&i.Created,
		&i.Expires,
	)
	return i, err
}

const getLatest = `-- name: GetLatest :many
SELECT snippet_id, title, content, created, expires
 	FROM snippets
 	WHERE expires > NOW()
 	ORDER BY created DESC
 	LIMIT 10
`

func (q *Queries) GetLatest(ctx context.Context) ([]Snippet, error) {
	rows, err := q.db.Query(ctx, getLatest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.SnippetID,
			&i.Title,
			&i.Content,
			&i.Created,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
