// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (uuid.UUID, error)
	GetById(ctx context.Context, snippetID uuid.UUID) (Snippet, error)
	GetLatest(ctx context.Context) ([]Snippet, error)
}

var _ Querier = (*Queries)(nil)
